site_name: My Docs
theme:
  name: material
  #Featuers
  features:
    # Performance options
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    # Navigation options
    #- navigation.tabs
    #- navigation.tabs.sticky #Force show tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    # Table of contents
    - toc.follow
    # Quality of life
    - navigation.top
  #Plugins
  plugins:
    - search
    - search.suggest
    - search.highlight
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
        #Additional options
        primary: black
        accent: blue  

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      # Additional options
      primary: black
      accent: blue  
nav:
  - home: index.md
  - new: test.md