site_name: My Docs

nav:
  - home: index.md
  - new: test.md

theme:
  name: material
  #Featuers
  features:
    # Performance options
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    # Navigation options
    #- navigation.tabs
    #- navigation.tabs.sticky #Force show tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    # Table of contents
    - toc.follow
    # Quality of life
    - navigation.top

  #Plugins
  plugins:
    - search
    - search.suggest
    - search.highlight

  palette:
    # Palette toggle for light mode
    - scheme: default
      #Additional options
      primary: black
      accent: blue  
      # Toggle switch
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
        

    # Palette toggle for dark mode
    - scheme: slate
      # Additional options
      primary: black
      accent: blue 
      # Toggle switch
      toggle:
        icon: material/brightness-4
        name: Switch to light mode